/*
 Timemap.js Copyright 2008 Nick Rabinowitz.
 Licensed under the MIT License (see LICENSE.txt)
*/
(function(){var window=this,undefined,Timeline=window.Timeline,DateTime=Timeline.DateTime,$=window.jQuery,mxn=window.mxn,Mapstraction=mxn.Mapstraction,LatLonPoint=mxn.LatLonPoint,BoundingBox=mxn.BoundingBox,Marker=mxn.Marker,Polyline=mxn.Polyline,E_ITEMS_LOADED="itemsloaded",GIP="http://www.google.com/intl/en_us/mapfiles/ms/icons/",TimeMap,TimeMapFilterChain,TimeMapDataset,TimeMapTheme,TimeMapItem;TimeMap=function(tElement,mElement,options){var tm=this,defaults={mapCenter:new LatLonPoint(0,0),mapZoom:0,
mapType:"physical",showMapTypeCtrl:true,showMapCtrl:true,syncBands:true,mapFilter:"hidePastFuture",centerOnItems:true,theme:"red",dateParser:"hybrid",checkResize:true,multipleInfoWindows:false},mapCenter;tm.mElement=mElement;tm.tElement=tElement;tm.datasets={};tm.chains={};tm.opts=options=$.extend(defaults,options);mapCenter=options.mapCenter;if(mapCenter.constructor!=LatLonPoint&&mapCenter.lat)options.mapCenter=new LatLonPoint(mapCenter.lat,mapCenter.lon);options.mapType=util.lookup(options.mapType,
TimeMap.mapTypes);options.mapFilter=util.lookup(options.mapFilter,TimeMap.filters);options.theme=TimeMapTheme.create(options.theme,options);tm.initMap()};TimeMap.version="2.1pre";var util=TimeMap.util={};TimeMap.init=function(config){var err="TimeMap.init: Either %Id or %Selector is required",defaults={options:{},datasets:[],bands:false,bandInfo:false,bandIntervals:"wk",scrollTo:"earliest"},state=TimeMap.state,intervals,tm,datasets=[],x,dsOptions,topOptions,dsId,bands=[],eventSource;config.mapSelector=
config.mapSelector||"#"+config.mapId;config.timelineSelector=config.timelineSelector||"#"+config.timelineId;if(state)state.setConfigFromUrl(config);config=$.extend(defaults,config);if(!config.bandInfo&&!config.bands){intervals=util.lookup(config.bandIntervals,TimeMap.intervals);config.bandInfo=[{width:"80%",intervalUnit:intervals[0],intervalPixels:70},{width:"20%",intervalUnit:intervals[1],intervalPixels:100,showEventText:false,overview:true,trackHeight:.4,trackGap:.2}]}tm=new TimeMap($(config.timelineSelector).get(0),
$(config.mapSelector).get(0),config.options);config.datasets.forEach(function(ds,x){dsOptions=$.extend({title:ds.title,theme:ds.theme,dateParser:ds.dateParser},ds.options);dsId=ds.id||"ds"+x;datasets[x]=tm.createDataset(dsId,dsOptions);if(x>0)datasets[x].eventSource=datasets[0].eventSource});tm.eventSource=datasets[0].eventSource;eventSource=datasets[0]&&datasets[0].eventSource||new Timeline.DefaultEventSource;if(config.bands){config.bands.forEach(function(band){if(band.eventSource!==null)band.eventSource=
eventSource});bands=config.bands}else config.bandInfo.forEach(function(bandInfo,x){if(!("eventSource"in bandInfo&&!bandInfo.eventSource))bandInfo.eventSource=eventSource;else bandInfo.eventSource=null;bands[x]=Timeline.createBandInfo(bandInfo);if(x>0&&util.TimelineVersion()=="1.2")bands[x].eventPainter.setLayout(bands[0].eventPainter.getLayout())});tm.initTimeline(bands);var loadManager=TimeMap.loadManager,callback=function(){loadManager.increment()};loadManager.init(tm,config.datasets.length,config);
config.datasets.forEach(function(data,x){var dataset=datasets[x],options=data.data||data.options||{},type=data.type||options.type,loaderClass=typeof type=="string"?TimeMap.loaders[type]:type,loader=new loaderClass(options);loader.load(dataset,callback)});return tm};TimeMap.prototype={initMap:function(){var tm=this,options=tm.opts,map,i;tm.map=map=new Mapstraction(tm.mElement,options.mapProvider);map.setCenterAndZoom(options.mapCenter,options.mapZoom);map.addControls({pan:options.showMapCtrl,zoom:options.showMapCtrl?
"large":false,map_type:options.showMapTypeCtrl});map.setMapType(options.mapType);if(options.multipleInfoWindows)map.setOption("enableMultipleBubbles",true);tm.getNativeMap=function(){return map.getMap()}},initTimeline:function(bands){var tm=this,timeline,opts=tm.opts,itemVisible=function(item){return item.visible},datasetVisible=function(item){return item.dataset.visible},eventClickHandler=function(x,y,evt){evt.item.openInfoWindow()},resizeTimerID,x,painter;for(x=1;x<bands.length;x++){if(opts.syncBands)bands[x].syncWith=
0;bands[x].highlight=true}tm.timeline=timeline=Timeline.create(tm.tElement,bands);for(x=0;x<timeline.getBandCount();x++){painter=timeline.getBand(x).getEventPainter().constructor;painter.prototype._showBubble=eventClickHandler}tm.addFilterChain("map",function(item){item.showPlacemark()},function(item){item.hidePlacemark()},null,null,[itemVisible,datasetVisible]);if(opts.mapFilter){tm.addFilter("map",opts.mapFilter);timeline.getBand(0).addOnScrollListener(function(){tm.filter("map")})}tm.addFilterChain("timeline",
function(item){item.showEvent()},function(item){item.hideEvent()},null,function(){tm.eventSource._events._index();timeline.layout()},[itemVisible,datasetVisible]);if(opts.timelineFilter)tm.addFilter("map",opts.timelineFilter);if(opts.checkResize)window.onresize=function(){if(!resizeTimerID)resizeTimerID=window.setTimeout(function(){resizeTimerID=null;timeline.layout()},500)}},parseDate:function(s){var d=new Date,eventSource=this.eventSource,parser=TimeMap.dateParsers.hybrid,hasEvents=eventSource.getCount()>
0?true:false;switch(s){case "now":break;case "earliest":case "first":if(hasEvents)d=eventSource.getEarliestDate();break;case "latest":case "last":if(hasEvents)d=eventSource.getLatestDate();break;default:d=parser(s)}return d},scrollToDate:function(d,lazyLayout,animated){var timeline=this.timeline,topband=timeline.getBand(0),x,time,layouts=[],band,minTime,maxTime;d=this.parseDate(d);if(d){time=d.getTime();for(x=0;x<timeline.getBandCount();x++){band=timeline.getBand(x);minTime=band.getMinDate().getTime();
maxTime=band.getMaxDate().getTime();layouts[x]=lazyLayout&&time>minTime&&time<maxTime}if(animated){var provider=util.TimelineVersion()=="1.2"?Timeline:SimileAjax,a=provider.Graphics.createAnimation(function(abs,diff){topband.setCenterVisibleDate(new Date(abs))},topband.getCenterVisibleDate().getTime(),time,1E3);a.run()}else topband.setCenterVisibleDate(d);for(x=0;x<layouts.length;x++)if(layouts[x])timeline.getBand(x).layout()}else if(lazyLayout)timeline.layout()},createDataset:function(id,options){var tm=
this,dataset=new TimeMapDataset(tm,options);dataset.id=id;tm.datasets[id]=dataset;if(tm.opts.centerOnItems){var map=tm.map;$(dataset).bind(E_ITEMS_LOADED,function(){map.autoCenterAndZoom()})}return dataset},each:function(f){var tm=this,id;for(id in tm.datasets)if(tm.datasets.hasOwnProperty(id))f(tm.datasets[id])},eachItem:function(f){this.each(function(ds){ds.each(function(item){f(item)})})},getItems:function(){var items=[];this.each(function(ds){items=items.concat(ds.items)});return items},setSelected:function(item){this.opts.selected=
item},getSelected:function(){return this.opts.selected},filter:function(chainId){var fc=this.chains[chainId];if(fc)fc.run()},addFilterChain:function(chainId,fon,foff,pre,post,chain){this.chains[chainId]=new TimeMapFilterChain(this,fon,foff,pre,post,chain)},removeFilterChain:function(chainId){delete this.chains[chainId]},addFilter:function(chainId,f){var fc=this.chains[chainId];if(fc)fc.add(f)},removeFilter:function(chainId,f){var fc=this.chains[chainId];if(fc)fc.remove(f)}};TimeMap.loadManager=new function(){var mgr=
this;mgr.init=function(tm,target,config){mgr.count=0;mgr.tm=tm;mgr.target=target;mgr.opts=config||{}};mgr.increment=function(){mgr.count++;if(mgr.count>=mgr.target)mgr.complete()};mgr.complete=function(){var tm=mgr.tm,opts=mgr.opts,func=opts.dataLoadedFunction;if(func)func(tm);else{tm.scrollToDate(opts.scrollTo,true);if(tm.initState)tm.initState();func=opts.dataDisplayedFunction;if(func)func(tm)}}};TimeMap.loaders={cb:{},cancel:function(callbackName){var namespace=TimeMap.loaders.cb;namespace[callbackName]=
function(){delete namespace[callbackName]}},cancelAll:function(){var loaderNS=TimeMap.loaders,namespace=loaderNS.cb,callbackName;for(callbackName in namespace)if(namespace.hasOwnProperty(callbackName))loaderNS.cancel(callbackName)},counter:0,base:function(options){var dummy=function(data){return data},loader=this;loader.parse=options.parserFunction||dummy;loader.preload=options.preloadFunction||dummy;loader.transform=options.transformFunction||dummy;loader.scrollTo=options.scrollTo||"earliest";loader.getCallbackName=
function(dataset,callback){var callbacks=TimeMap.loaders.cb,callbackName="_"+TimeMap.loaders.counter++;callback=callback||function(){dataset.timemap.scrollToDate(loader.scrollTo,true)};callbacks[callbackName]=function(result){var items=loader.parse(result);items=loader.preload(items);dataset.loadItems(items,loader.transform);callback();delete callbacks[callbackName]};return callbackName};loader.getCallback=function(dataset,callback){var callbackName=loader.getCallbackName(dataset,callback);return TimeMap.loaders.cb[callbackName]};
loader.cancel=function(){TimeMap.loaders.cancel(loader.callbackName)}},basic:function(options){var loader=new TimeMap.loaders.base(options);loader.data=options.items||options.value||[];loader.load=function(dataset,callback){this.getCallback(dataset,callback)(this.data)};return loader},remote:function(options){var loader=new TimeMap.loaders.base(options);loader.opts=$.extend({},options,{type:"GET",dataType:"text"});loader.load=function(dataset,callback){loader.callbackName=loader.getCallbackName(dataset,
callback);loader.opts.success=TimeMap.loaders.cb[loader.callbackName];$.ajax(loader.opts)};return loader}};TimeMapFilterChain=function(timemap,fon,foff,pre,post,chain){var fc=this,dummy=$.noop;fc.timemap=timemap;fc.chain=chain||[];fc.on=fon||dummy;fc.off=foff||dummy;fc.pre=pre||dummy;fc.post=post||dummy};TimeMapFilterChain.prototype={add:function(f){return this.chain.push(f)},remove:function(f){var chain=this.chain,i=f?chain.indexOf(f):chain.length-1;return chain.splice(i,1)},run:function(){var fc=
this;fc.pre();var chain=fc.chain;if(!chain.length)return;fc.timemap.eachItem(function(item){if(chain.every(function(chainLink){return chainLink(item)}))fc.on(item);else fc.off(item)});fc.post()}};TimeMap.filters={hidePastFuture:function(item){return item.onVisibleTimeline()},hideFuture:function(item){var maxVisibleDate=item.timeline.getBand(0).getMaxVisibleDate().getTime(),itemStart=item.getStartTime();if(itemStart!==undefined)return itemStart<maxVisibleDate;return true},showMomentOnly:function(item){var topband=
item.timeline.getBand(0),momentDate=topband.getCenterVisibleDate().getTime(),itemStart=item.getStartTime(),itemEnd=item.getEndTime();if(itemStart!==undefined)return itemStart<momentDate&&(itemEnd>momentDate||itemStart>momentDate);return true}};TimeMapDataset=function(timemap,options){var ds=this;ds.timemap=timemap;ds.eventSource=new Timeline.DefaultEventSource;ds.items=[];ds.visible=true;ds.opts=options=$.extend({},timemap.opts,options);options.dateParser=util.lookup(options.dateParser,TimeMap.dateParsers);
options.theme=TimeMapTheme.create(options.theme,options)};TimeMapDataset.prototype={getItems:function(index){var items=this.items;return index===undefined?items:index in items?items[index]:null},getTitle:function(){return this.opts.title},each:function(f){this.items.forEach(f)},loadItems:function(data,transform){if(data){var ds=this;data.forEach(function(item){ds.loadItem(item,transform)});$(ds).trigger(E_ITEMS_LOADED)}},loadItem:function(data,transform){if(transform)data=transform(data);if(data){var ds=
this,item;data.options=$.extend({},ds.opts,{title:null},data.options);item=new TimeMapItem(data,ds);ds.items.push(item);return item}}};TimeMapTheme=function(options){var defaults={color:"#FE766A",lineOpacity:1,lineWeight:2,fillOpacity:.4,eventTextColor:null,eventIconPath:"timemap/images/",eventIconImage:"red-circle.png",classicTape:false,icon:GIP+"red-dot.png",iconSize:[32,32],iconShadow:GIP+"msmarker.shadow.png",iconShadowSize:[59,32],iconAnchor:[16,33]};var settings=$.extend(defaults,options);defaults=
{lineColor:settings.color,fillColor:settings.color,eventColor:settings.color,eventIcon:settings.eventIcon||settings.eventIconPath+settings.eventIconImage};return $.extend(defaults,settings)};TimeMapTheme.create=function(theme,options){theme=util.lookup(theme,TimeMap.themes);if(!theme)return new TimeMapTheme(options);if(options){var clone=false,key;for(key in options)if(theme.hasOwnProperty(key)){clone={};break}if(clone){for(key in theme)if(theme.hasOwnProperty(key))clone[key]=options[key]||theme[key];
clone.eventIcon=options.eventIcon||clone.eventIconPath+clone.eventIconImage;return clone}}return theme};TimeMapItem=function(data,dataset){var item=this,options=$.extend({type:"none",description:"",infoPoint:null,infoHtml:"",infoUrl:"",openInfoWindow:data.options.infoUrl?TimeMapItem.openInfoWindowAjax:TimeMapItem.openInfoWindowBasic,infoTemplate:'<div class="infotitle">{{title}}</div>'+'<div class="infodescription">{{description}}</div>',templatePattern:/\{\{([^}]+)\}\}/,closeInfoWindow:TimeMapItem.closeInfoWindowBasic},
data.options),tm=dataset.timemap,theme=options.theme=TimeMapTheme.create(options.theme,options),parser=options.dateParser,eventClass=Timeline.DefaultEventSource.Event,start=data.start,end=data.end,eventIcon=theme.eventIcon,textColor=theme.eventTextColor,title=options.title=data.title||"Untitled",event=null,instant,placemarks=[],pdataArr=[],pdata=null,type="",point=null,i;item.dataset=dataset;item.map=tm.map;item.timeline=tm.timeline;item.opts=options;start=start?parser(start):null;end=end?parser(end):
null;instant=!end;if(start!==null){if(util.TimelineVersion()=="1.2")event=new eventClass(start,end,null,null,instant,title,null,null,null,eventIcon,theme.eventColor,theme.eventTextColor);else{if(!textColor)textColor=theme.classicTape&&!instant?"#FFFFFF":"#000000";event=new eventClass({start:start,end:end,instant:instant,text:title,icon:eventIcon,color:theme.eventColor,textColor:textColor})}event.item=item;if(!options.noEventLoad)dataset.eventSource.add(event)}item.event=event;function createPlacemark(pdata){var placemark=
null,type="",point=null,pBounds;if(pdata.point){var lat=pdata.point.lat,lon=pdata.point.lon;if(lat===undefined||lon===undefined)return placemark;point=new LatLonPoint(parseFloat(lat),parseFloat(lon));placemark=new Marker(point);placemark.setLabel(pdata.title);placemark.addData(theme);type="marker"}else if(pdata.polyline||pdata.polygon){var points=[],isPolygon="polygon"in pdata,line=pdata.polyline||pdata.polygon,x;pBounds=new BoundingBox;if(line&&line.length){for(x=0;x<line.length;x++){point=new LatLonPoint(parseFloat(line[x].lat),
parseFloat(line[x].lon));points.push(point);pBounds.extend(point)}placemark=new Polyline(points);placemark.addData({color:theme.lineColor,width:theme.lineWeight,opacity:theme.lineOpacity,closed:isPolygon,fillColor:theme.fillColor,fillOpacity:theme.fillOpacity});type=isPolygon?"polygon":"polyline";point=isPolygon?pBounds.getCenter():points[Math.floor(points.length/2)]}}else if("overlay"in pdata){var sw=new LatLonPoint(parseFloat(pdata.overlay.south),parseFloat(pdata.overlay.west)),ne=new LatLonPoint(parseFloat(pdata.overlay.north),
parseFloat(pdata.overlay.east));pBounds=new BoundingBox(sw.lat,sw.lon,ne.lat,ne.lon);tm.map.addImageOverlay("img"+(new Date).getTime(),pdata.overlay.image,theme.lineOpacity,sw.lon,sw.lat,ne.lon,ne.lat);type="overlay";point=pBounds.getCenter()}return{"placemark":placemark,"type":type,"point":point}}if("placemarks"in data)pdataArr=data.placemarks;else["point","polyline","polygon","overlay"].forEach(function(type){if(type in data){pdata={};pdata[type]=data[type];pdataArr.push(pdata)}});pdataArr.forEach(function(pdata){pdata.title=
pdata.title||title;var p=createPlacemark(pdata);if(p){point=point||p.point;type=type||p.type;if(p.placemark)placemarks.push(p.placemark)}});options.type=placemarks.length>1?"array":type;options.infoPoint=options.infoPoint?new LatLonPoint(parseFloat(options.infoPoint.lat),parseFloat(options.infoPoint.lon)):point;placemarks.forEach(function(placemark){placemark.item=item;placemark.click.addHandler(function(){item.openInfoWindow()});if(!options.noPlacemarkLoad){if(util.getPlacemarkType(placemark)=="marker")tm.map.addMarker(placemark);
else tm.map.addPolyline(placemark);placemark.hide()}});item.placemark=placemarks.length==1?placemarks[0]:placemarks.length?placemarks:null;item.getNativePlacemark=function(){var placemark=item.placemark;return placemark&&(placemark.proprietary_marker||placemark.proprietary_polyline)};item.getType=function(){return options.type};item.getTitle=function(){return options.title};item.getInfoPoint=function(){return options.infoPoint||item.map.getCenter()};item.getStart=function(){return item.event?item.event.getStart():
null};item.getEnd=function(){return item.event?item.event.getEnd():null};item.getStartTime=function(){var start=item.getStart();if(start)return start.getTime()};item.getEndTime=function(){var end=item.getEnd();if(end)return end.getTime()};item.isSelected=function(){return tm.getSelected()===item};item.visible=true;item.placemarkVisible=false;item.eventVisible=true;item.openInfoWindow=function(){options.openInfoWindow.call(item);tm.setSelected(item)};item.closeInfoWindow=function(){options.closeInfoWindow.call(item);
tm.setSelected(undefined)}};TimeMapItem.prototype={showPlacemark:function(){var item=this,f=function(placemark){if(placemark.api)placemark.show()};if(item.placemark&&!item.placemarkVisible){if(item.getType()=="array")item.placemark.forEach(f);else f(item.placemark);item.placemarkVisible=true}},hidePlacemark:function(){var item=this,f=function(placemark){if(placemark.api)placemark.hide()};if(item.placemark&&item.placemarkVisible){if(item.getType()=="array")item.placemark.forEach(f);else f(item.placemark);
item.placemarkVisible=false}item.closeInfoWindow()},showEvent:function(){var item=this,event=item.event;if(event&&!item.eventVisible){item.timeline.getBand(0).getEventSource()._events._events.add(event);item.eventVisible=true}},hideEvent:function(){var item=this,event=item.event;if(event&&item.eventVisible){item.timeline.getBand(0).getEventSource()._events._events.remove(event);item.eventVisible=false}},scrollToStart:function(animated){var item=this;if(item.event)item.dataset.timemap.scrollToDate(item.getStart(),
false,animated)},getInfoHtml:function(){var opts=this.opts,html=opts.infoHtml,patt=opts.templatePattern,match;if(!html){html=opts.infoTemplate;match=patt.exec(html);while(match){html=html.replace(match[0],opts[match[1]]||"");match=patt.exec(html)}opts.infoHtml=html}return html},onVisibleTimeline:function(){var item=this,topband=item.timeline.getBand(0),maxVisibleDate=topband.getMaxVisibleDate().getTime(),minVisibleDate=topband.getMinVisibleDate().getTime(),itemStart=item.getStartTime(),itemEnd=item.getEndTime();
return itemStart!==undefined?itemStart<maxVisibleDate&&(itemEnd>minVisibleDate||itemStart>minVisibleDate):true}};TimeMapItem.openInfoWindowBasic=function(){var item=this,html=item.getInfoHtml(),ds=item.dataset,placemark=item.placemark;if(!item.onVisibleTimeline())ds.timemap.scrollToDate(item.getStart());if(item.getType()=="marker"&&placemark.api){placemark.setInfoBubble(html);placemark.openBubble();item.closeHandler=placemark.closeInfoBubble.addHandler(function(){ds.timemap.setSelected(undefined);
placemark.closeInfoBubble.removeHandler(item.closeHandler)})}else{item.map.openBubble(item.getInfoPoint(),html);item.map.tmBubbleItem=item}};TimeMapItem.openInfoWindowAjax=function(){var item=this;if(!item.opts.infoHtml&&item.opts.infoUrl){$.get(item.opts.infoUrl,function(result){item.opts.infoHtml=result;item.openInfoWindow()});return}item.openInfoWindow=function(){TimeMapItem.openInfoWindowBasic.call(item);item.dataset.timemap.setSelected(item)};item.openInfoWindow()};TimeMapItem.closeInfoWindowBasic=
function(){var item=this;if(item.getType()=="marker")item.placemark.closeBubble();else if(item==item.map.tmBubbleItem){item.map.closeBubble();item.map.tmBubbleItem=null}};TimeMap.util.getTagValue=function(n,tag,ns){return util.getNodeList(n,tag,ns).first().text()};TimeMap.util.nsMap={};TimeMap.util.getNodeList=function(n,tag,ns){var nsMap=TimeMap.util.nsMap;n=n.jquery?n[0]:n;return!n?$():!ns?$(tag,n):n.getElementsByTagNameNS&&nsMap[ns]?$(n.getElementsByTagNameNS(nsMap[ns],tag)):$(n.getElementsByTagName(ns+
":"+tag))};TimeMap.util.makePoint=function(coords,reversed){var latlon=null;if(coords.lat&&coords.lng)latlon=[coords.lat(),coords.lng()];if($.type(coords)=="array")latlon=coords;if(!latlon){coords=$.trim(coords);if(coords.indexOf(",")>-1)latlon=coords.split(",");else latlon=coords.split(/[\r\n\f ]+/)}if(latlon.length>2)latlon=latlon.slice(0,2);if(reversed)latlon.reverse();return{"lat":$.trim(latlon[0]),"lon":$.trim(latlon[1])}};TimeMap.util.makePoly=function(coords,reversed){var poly=[],latlon,x,
coordArr=$.trim(coords).split(/[\r\n\f ]+/);for(x=0;x<coordArr.length;x++){latlon=coordArr[x].indexOf(",")>0?coordArr[x].split(","):[coordArr[x],coordArr[++x]];if(latlon.length>2)latlon=latlon.slice(0,2);if(reversed)latlon.reverse();poly.push({"lat":latlon[0],"lon":latlon[1]})}return poly};TimeMap.util.formatDate=function(d,precision){precision=precision||3;var str="";if(d){var yyyy=d.getUTCFullYear(),mo=d.getUTCMonth(),dd=d.getUTCDate();if(yyyy<1E3)return yyyy<1?yyyy*-1+"BC":yyyy+"";if(d.toISOString&&
precision==3)return d.toISOString();var pad=function(num){return(num<10?"0":"")+num};str+=yyyy+"-"+pad(mo+1)+"-"+pad(dd);if(precision>1){var hh=d.getUTCHours(),mm=d.getUTCMinutes(),ss=d.getUTCSeconds();str+="T"+pad(hh)+":"+pad(mm);if(precision>2)str+=pad(ss);str+="Z"}}return str};TimeMap.util.TimelineVersion=function(){return Timeline.version||(Timeline.DurationEventPainter?"1.2":"2.2.0")};TimeMap.util.getPlacemarkType=function(pm){return pm.constructor==Marker?"marker":pm.constructor==Polyline?pm.closed?
"polygon":"polyline":false};TimeMap.util.lookup=function(key,map){return typeof key=="string"?map[key]:key};if(![].indexOf)Array.prototype.indexOf=function(el){var a=this,i=a.length;while(--i>=0)if(a[i]===el)break;return i};if(![].forEach)Array.prototype.forEach=function(f){var a=this,i;for(i=0;i<a.length;i++)if(i in a)f(a[i],i,a)};TimeMap.intervals={sec:[DateTime.SECOND,DateTime.MINUTE],min:[DateTime.MINUTE,DateTime.HOUR],hr:[DateTime.HOUR,DateTime.DAY],day:[DateTime.DAY,DateTime.WEEK],wk:[DateTime.WEEK,
DateTime.MONTH],mon:[DateTime.MONTH,DateTime.YEAR],yr:[DateTime.YEAR,DateTime.DECADE],dec:[DateTime.DECADE,DateTime.CENTURY]};TimeMap.mapTypes={normal:Mapstraction.ROAD,satellite:Mapstraction.SATELLITE,hybrid:Mapstraction.HYBRID,physical:Mapstraction.PHYSICAL};TimeMap.dateParsers={gregorian:function(s){if(!s||typeof s!="string")return null;var bc=Boolean(s.match(/b\.?c\.?/i)),year=parseInt(s,10),d;if(!isNaN(year)){if(bc)year=1-year;d=new Date(0);d.setUTCFullYear(year);return d}else return null},hybrid:function(s){if(s instanceof
Date)return s;var parsers=TimeMap.dateParsers,d=new Date(typeof s=="number"?s:Date.parse(parsers.fixChromeBug(s)));if(isNaN(d))if(typeof s=="string"){if(s.match(/^-?\d{1,6} ?(a\.?d\.?|b\.?c\.?e?\.?|c\.?e\.?)?$/i))d=parsers.gregorian(s);else try{d=parsers.iso8601(s)}catch(e){d=null}if(!d&&s.match(/^\d{7,}$/))d=new Date(parseInt(s,10))}else return null;return d},iso8601:DateTime.parseIso8601DateTime,fixChromeBug:function(s){return Date.parse("-200")==Date.parse("200")?typeof s=="string"&&s.substr(0,
1)=="-"?null:s:s}};TimeMap.themes={red:new TimeMapTheme,blue:new TimeMapTheme({icon:GIP+"blue-dot.png",color:"#5A7ACF",eventIconImage:"blue-circle.png"}),green:new TimeMapTheme({icon:GIP+"green-dot.png",color:"#19CF54",eventIconImage:"green-circle.png"}),ltblue:new TimeMapTheme({icon:GIP+"ltblue-dot.png",color:"#5ACFCF",eventIconImage:"ltblue-circle.png"}),purple:new TimeMapTheme({icon:GIP+"purple-dot.png",color:"#8E67FD",eventIconImage:"purple-circle.png"}),orange:new TimeMapTheme({icon:GIP+"orange-dot.png",
color:"#FF9900",eventIconImage:"orange-circle.png"}),yellow:new TimeMapTheme({icon:GIP+"yellow-dot.png",color:"#ECE64A",eventIconImage:"yellow-circle.png"}),pink:new TimeMapTheme({icon:GIP+"pink-dot.png",color:"#E14E9D",eventIconImage:"pink-circle.png"})};window.TimeMap=TimeMap;window.TimeMapFilterChain=TimeMapFilterChain;window.TimeMapDataset=TimeMapDataset;window.TimeMapTheme=TimeMapTheme;window.TimeMapItem=TimeMapItem})();
